//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FONDO_INVERSION
    {
        public decimal ID_FONDO { get; set; }
        public decimal ID_MONEDA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<decimal> CAPITAL_INVERSIONISTAS { get; set; }
        public Nullable<decimal> CAPITAL_PRESTADO { get; set; }
        public Nullable<decimal> CAPITAL_DISPONIBLE { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual MONEDA MONEDA { get; set; }
    }
}
