//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_INVERSION
    {
        public decimal ID_PAGO_INVERSION { get; set; }
        public decimal ID_INVERSION { get; set; }
        public decimal NUMERO_PAGO { get; set; }
        public System.DateTime FECHA_PAGO_PROGRAMADA { get; set; }
        public decimal MONTO_INTERES { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO_REAL { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual INVERSION INVERSION { get; set; }
    }
}
