//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTAMO()
        {
            this.PAGO_PRESTAMO = new HashSet<PAGO_PRESTAMO>();
        }
    
        public decimal ID_PRESTAMO { get; set; }
        public decimal ID_ENTIDAD { get; set; }
        public decimal ID_MONEDA { get; set; }
        public decimal MONTO_PRESTAMO { get; set; }
        public decimal PLAZO_DIAS { get; set; }
        public decimal TASA_INTERES { get; set; }
        public string MODALIDAD_PAGO { get; set; }
        public System.DateTime FECHA_PRESTAMO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> MONTO_INTERESES { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public decimal ID_USUARIO_CREA { get; set; }
    
        public virtual ENTIDAD_FINANCIERA ENTIDAD_FINANCIERA { get; set; }
        public virtual MONEDA MONEDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO_PRESTAMO> PAGO_PRESTAMO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
